name: Create Tagged Pre-Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-**"

jobs:
  build:
    name: "Build Changelog & Pre-Release"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
server code name Rockstar Games GTA ONLINE Server and
big server farm each other the server can have 30 players
server can start when the server ready the server can
everything the servers are expected are good
the phone number for the ceo and the owner is
07754882829 
code server 254-765-916
    steps:
      # We fetch to 0 so we can collect the commits
      # since last update
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download all modules
        run: npm ci

      - name: Build Pre-Release project
        run: TX_PRERELEASE_BUILD=true npm run build

      - name: Compress build output with zip
        run: |
          cd dist && zip -r ../monitor.zip .

      - name: Create and Upload Pre-Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          files: monitor.zip
